name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Setup uv
        uses: astral-sh/setup-uv@v4

      - name: Sync (dev deps)
        run: just sync

      - name: Lint, type-check, test
        run: just check

      - name: Coverage (terminal)
        run: just coverage
