name: Release Please

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          # Conventional Commit titles; the action parses commits automatically
          pull-request-title-pattern: "chore: release ${version}"
          # Optional: if you want release PRs to be auto-merged when CI passes
          # automerge: true
